### ISSUE TITLE
Import/Export indexer database

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1062]
Create Import and Export functions for the database indexer, in order to be able to implement snapshot/state synchronization. 

The indexer must be able to dump the entire database into a file. The file can then be sent via p2p network to nodes that are bootstrapping, in addition to a statedb export. The new node can then just import both databases and start working as synced.

**Comment by mvdan** [comment]
I'm not sure I follow. If a node needs to get the entire state/chain to synchronize anyway, why not rebuild the indexer database from that directly?

You're right that getting a prepared and compressed version of an up-to-date indexer database is likely faster, but it's also extra work to prepare it, and an amount of extra code to support creating it and consuming it. Assuming that walking the entire chain can be done relatively efficiently, I would personally do that instead, because it works without requiring an extra p2p sync mechanism.

**Comment by altergui** [comment]
fixed in #1201
