### ISSUE TITLE
feature: Report circuit artifacts to use for a started process with rolling census

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#327]
Anonymous voting uses a process with a rolling census that is closed once the process starts.  We can have different circuit builds for different census sizes.  The client needs to figure out which circuit artifacts to use for a given process, and we can give that information via some API endpoint.
What the node needs to do is: get the census size, and pick the smaller circuit artifacts that supports that size from the `VochainGenesis.CircuitsConfig` in the vochain genesis.  That information should be supplied to the user via an API.

I've been looking at different endpoints and I think the best place to put this information is in the `getProcessInfo` endpoint in the scrutinizer.  This would would involve:
1. In `Scrutinizer.updateProcess` if the process is rolling, store the current census size (This one is optional, but it would allow querying the current rolling census size.  This would require that the Scrutinizer updates the census size on every Commit.  It could be done via a new event `OnGrowRollingCensus`, or by the Scrutinizer querying all the processes with rolling census with StartBlock < currentBlock and updating the census sizes from there).
2. In `Scrutinizer.OnProcessesStart` if the process is anonymous, figure out the circuit config and store the index in the process.
3. Extend `indexertypes.Process` with rolling census size, and circuit config index
4. In `Scrutinizer.ProcessInfo`, if the process is anonymous and started, query the Genesis.CircuitConfigs for the stored index, and return the data.

**Comment by ed255** [comment]
@p4u Do you think the described proposal makes sense?  Or is there a better place to serve this information to the user?

**Comment by p4u** [comment]
I'd add two new fields to `models.Process`: 

+ censusSize: set by the process owner, since we cannot enforce the correctness of this value, no more votes should be allowed for a process once the censusSize has been reached. This value will be used to set the price for an election.
+ rollingCensusSize: once the process starts, if preRegister is true, is set with the number of leafs that the rolling census contains. This value is used to select the zkSnarks artifacts to use.

The scrutinizer/indexer should also be extended with these two values. There is a vochain event callback on the scrutinizer that synchronizes the scrutinizer database with the state when there are changes on the state Process.

Regarding the API, I think we should either define a new method within the "vote API" or reuse `getProcessKeys` https://docs.vocdoni.io/architecture/services/gateway.html#vote-api

The scrutinizer should be synced with the state, but the API call could just take the value from the state (not the scrutinizer database) as `getProcessKeys` does.
