### ISSUE TITLE
Get rid of multirpc

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#367]
MultiRPC (https://github.com/vocdoni/vocdoni-node/tree/master/multirpc) is deprecated (in favor of the new `httpRouter` package). So we should get rid of the whole directory `multirpc/`. IPFSsync is currently the only package that requires multirpc, cause it uses subpub as a transport layer for messages. 

Can we complete deprecated subpub with PR #363 (use GossipSub)? If not can move the `multirpc/subpub` directory to `/subpub` and modify ipfsSync accordingly.

**Comment by altergui** [comment]
wonderful! while working on gossipsub, i wondered about this multirpc and up to which point was it used and useful :)

**Comment by altergui** [comment]
i did the trivial version first, simply renaming `subpub` module: https://github.com/vocdoni/vocdoni-node/pull/363#commits-pushed-5835fd7 so there's a lot less clutter now.
i'll continue with refactoring, this is what i have in mind so far (not sure if everything makes sense or is possible):
* drop the `transports` abstraction and interfaces, i.e. make ipfssync.go interact directly with subpub
* greatly simplify subpub, dropping the ps.Peers and all the connection handling, since it can be simply reduced to a gossipsub topic for broadcasts and a couple simple functions for unicasts.

**Comment by altergui** [comment]
some progress: https://github.com/vocdoni/vocdoni-node/pull/363#event-5621874346
* no more `transports` package, there's only `subpub` package now
* discarded lots of unused code
* gossipsub stuff is still kind of spread around, needs more work

**Comment by altergui** [comment]
* dropped `ps.Peers` with significant refactoring.

everything still works as expected, at least on the smallest test possible of 3 nodes.

my next step to remove the leftovers from `multirpc` would be to dissolve the `transport.go`, most of the functions there are just abstractions and the ones with substance can be moved somewhere else.
...but maybe i'm refactoring waaay too much?

in any case, this has been a wonderful dive into Go :)

**Comment by altergui** [comment]
i went ahead and finished this crazy refactoring.

squashed everything into a single commit, with a long description.

https://github.com/vocdoni/vocdoni-node/pull/363/commits/b2a95e2832bc4b40e601d62cbf8b936d40662ca6

**Comment by altergui** [comment]
multirpc is gone for good
