### ISSUE TITLE
getEnvelope does not find the envelope

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#538]
Envelopes are not found on the SQL database:

```
curl https://gw1.dev.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getEnvelope", "nullifier": "06b668c9333d4998a52d8185febe7f76f12822edc0fc16356db6083ff645a9ee", "timestamp":'$(date +%s)'}}'

{"response":{"message":"cannot get envelope: No data found for this key","ok":false,"request":"req008235","timestamp":1649083792},"id":"req008235","signature":"f28e5f754a0ee1d8e65528c9cff93c07cb6e6b55d11e0d6c0228e8f25ff4ab9c1957e52b66f213a0c312e5d29ed395ac87ae56138b3e0a8dbdde6ebddfc37b3600"}
```

This can be repdroduced on DEV (in sync with master).
The envelope exist on the blockchain https://explorer.dev.vocdoni.net/transaction/74451/175
06b668c9333d4998a52d8185febe7f76f12822edc0fc16356db6083ff645a9ee But it cannot be queried.

**Comment by mvdan** [comment]
I don't think this is related to the sqlite code I've added recently; "No data found for this key" is a badgerhold error, so presumably this is just badgerhold.

Has this happened with any other nullifier?

Do we know if the entry actually exists in the badgerhold database? It could be that for some reason it wasn't inserted properly.

I don't think badger or badgerhold have any CLI to debug this from outside the Go process, but sqlite does, so I just pulled `/app/run/dev/vochain/scrutinizer-sqlite` into my local machine and tried to find that vote envelope:

```
> select hex(nullifier) from vote_references;
[...]
064F8332C3735279CDC05F28B57F0C341AADC8454C0CF9B22959D2B18AAE60DB
06631DFDC2AE05488AE7823F87995AEA26AB7172A397A3DBFDC633D075A924D9
06A7A9601CFDC383B5F3108EBAF74DA06175A8AA25FD912A0CA0649CD8401200
075BFFA2EA6082FA4176978618B947E369EB847F318CE1B1691B2E39FDD66A37
076ED1F56FAE1B9C82089AB569CA7C1DA9FC3E74FDBF161B5962DCFBF3E1A4EF
[...]
```

It's not there - so the bug doesn't seem to be with the DB or the queries, because it appears neither badgerhold nor sqlite have that vote reference. I guess the code never inserted that entry into either DB at all.

**Comment by p4u** [comment]
We should dig into this issue... I can reproduce it with the last develpments on master. @jordipainan ideas?
```
curl https://gw1.dev.vocdoni.net/dvote -X POST -H Content-Type:application/json --data '{"id": "req00'$RANDOM'", "request": {"method": "getEnvelope", "nullifier": "69b11b3a8d162ca197fda9378b0a96631ae50e488716f5d02c6ff26c3faefd1f", "timestamp":'$(date +%s)'}}'

{"response":{"message":"cannot get envelope: No data found for this key","ok":false,"request":"req0015144","timestamp":1651603179},"id":"req0015144","signature":"8e4352de0cb027060436d4c096cc0856232f67c98b4ef19730156fdb387561fb6c89177ecaf7e4af27c0b830661d3dee188c74fa49b5b7e46e7db1911860942f00"}
```

**Comment by p4u** [comment]
Looks like the problem might be the returned nullifier by the gateway, cause getEnvelope works fine if queried the correct nullifier https://explorer.dev.vocdoni.net/envelope/2f7910a20e0ff601acbe2722fc0d448f39d79c6ffdccf762f43fedb6faa90b45

**Comment by p4u** [comment]
Problem is I cannot simply tell testing.B/B.RunParallel to only run for 100 times.
