### ISSUE TITLE
bug: BenchmarkVochain tries to send too many votes, causing list index panic

### ISSUE THREAD

**Issue by randomshinichi** [vocdoni/vocdoni-node#541]
**Describe the bug**
Check out https://github.com/randomshinichi/vocdoni-node/tree/fix/benchmark

**To Reproduce (please complete the following information)**
`go test ./benchmark -test.bench=^BenchmarkVochain100Votes$`

launch.json
```
{
            "name": "BenchmarkVochain",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceFolder}/benchmark",
            "args": [
                "-test.bench",
                "^BenchmarkVochain100Votes$"
            ]
        },
```

**Current behavior**
`panic: runtime error: index out of range [100] with length 100`

**Expected behavior**
benchmark shows the time cost of submitting one vote to an ideal running chain

**Additional context**
Problem is I cannot simply tell testing.B/B.RunParallel to only run for 100 times. Which points to the code author maybe misunderstanding how Golang authors intended testing.B to be used, or my incomplete understanding of something.
See [Dave Cheney's introductory blogpost](https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go).

The author does not seem to be aware that b.N is incremented automatically by the testing package.

Why can't one simply use for.... count ++? Would like context from @p4u about PR #77 because it seems to be where the RunParallel complication and atomic count++ complication was introduced.

**Comment by p4u** [comment]
> Problem is I cannot simply tell testing.B/B.RunParallel to only run for 100 times.

If I understand correctly the problem, I think Golang benchmarks are **NOT** designed to execute a code only a specific number of times. It depends on the number of CPUs and other parameters and its hard to determine the exact number of times the benchmark is finally executed. You can write a benchmark function that makes 100 iterations but you cannot know how many times this function is called.

In the example of the link provided, the benchmark function is fully independent, meaning that every benchmark thread runs 10 times but multiple can run in parallel with no dependencies among them.

```
// from fib_test.go
func BenchmarkFib10(b *testing.B) {
        // run the Fib function b.N times
        for n := 0are; n < b.N; n++ {
                Fib(10)
        }
}
```

However as far as I understand, the benchmark you are working on tries to send 100 votes by using multiple threads, so you cannot know how many votes are actually sent. The benchmark function is not independent so if thread 1 uses vote 1, thread 2 cannot use vote 1.

In order to implement a benchmark like this I'd instead use CSP voting and provide the CSP privKey to every benchmark thread so it can create randomly a new batch of voter keys, create the CSP proofs on the fly and vote. This way you can have up to N threads working in parallel without the current limit.

**Comment by randomshinichi** [comment]
We've had this backwards all the time.

We want to benchmark the vote processing time. We should let Golang benchmark framework determine the number of votes to send `b.N`, and start the timer just when the votes are about to be sent `b.ResetTimer()`.

This has been implemented for both types of census

CSP census
https://github.com/randomshinichi/vocdoni-node/commit/cb712d186fb69879b035a9435b61e2756792f9e3
IPFS census
https://github.com/randomshinichi/vocdoni-node/commit/9987a1dbb4387a70de631ab04a1bcaaac1d0dc77
