### ISSUE TITLE
goroutine leak in gateway mode

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#627]
![image](https://user-images.githubusercontent.com/2815267/194832837-3e3dac89-cbbe-45d6-a101-adfa1374f584.png)

nodes running in gateway mode sometimes start leaking goroutines.

looking at the graphs, this does not happen all the time, there's some kind of trigger.

also, this only happens in gateways, nodes running in other modes (miner, oracle) don't leak.

@p4u and @mvdan point the finger to libp2p, after digging into this with pprof. thanks a million! will chase this and propose PR

**Comment by p4u** [comment]
[goroutine_gw3.pprof.gz](https://github.com/vocdoni/vocdoni-node/files/9749569/goroutine_gw3.pprof.gz)
added a goroutine pprof debug log of a gateway suffering from the leak

**Comment by altergui** [comment]
looking at that log, this is the goroutine that is piling up

```
goroutine 4336032328 [select, 421 minutes]:
github.com/libp2p/go-libp2p-kad-dht/providers.(*ProviderManager).AddProvider(0xc00494ef00, {0x3cdeb60, 0xc065728420}, {0xc0193ba3f0, 0x24, 0x30}, {{0xc087c1db00, 0x26}, {0x0, 0x0, ...}})
	github.com/libp2p/go-libp2p-kad-dht@v0.16.0/providers/providers_manager.go:242 +0x1d4
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).handleAddProvider(0xc0059c6000, {0x3cdeb60, 0xc065728420}, {0xc087c1db00, 0x26}, 0xc01bdf2400)
	github.com/libp2p/go-libp2p-kad-dht@v0.16.0/handlers.go:362 +0x403
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).handleNewMessage(0xc0059c6000, {0x3d35468, 0xc01bdf2380})
	github.com/libp2p/go-libp2p-kad-dht@v0.16.0/dht_net.go:121 +0xa03
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).handleNewStream(0xc061767fc0, {0x3d35468, 0xc01bdf2380})
	github.com/libp2p/go-libp2p-kad-dht@v0.16.0/dht_net.go:26 +0x25
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1({0xc01ee77e60, 0xf}, {0x7fd884268260, 0xc01bdf2380})
	github.com/libp2p/go-libp2p@v0.20.3/p2p/host/basic/basic_host.go:568 +0x76
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	github.com/libp2p/go-libp2p@v0.20.3/p2p/host/basic/basic_host.go:411 +0x725
```

and it started leaking at uptime=1425mins (23h45m)
at a rate of ~400 per minute, for about 20 mins (uptime=1445mins)
then slowed down to ~100 per minute, and leaked at that steady rate until the moment the pprof dump was taken by pau

**Comment by mvdan** [comment]
Yes - they are libp2p streams, which use goroutines, and those are somehow getting leaked. That's what @p4u and I found last week.

I suggested that we first upgrade libp2p to see if that fixed the issue, but it seems like the leak is still here, so we should investigate further. @altergui let me know if you get stuck and I can take a closer look at the code today or tomorrow.

**Comment by mvdan** [comment]
Also, here are my two guesses at what is causing the leaks:

1) The libp2p connections are good - we are just opening too many connections and keeping them running. This could be, for example, because a bug results in our nodes connecting to each other repeatedly. Or because there is a node that keeps opening connections.

2) The libp2p connections are stalled or broken, and we somehow fail to stop the goroutines which operate them. The connections might be stalling/breaking quickly when the internet connection has issues, or when some other nodes crash, for example.

**Comment by altergui** [comment]
the thing is, this simple goroutine is the one blocked, AFAIU due to the chan pm.newprovs not being read
```
// AddProvider adds a provider
func (pm *ProviderManager) AddProvider(ctx context.Context, k []byte, provInfo peer.AddrInfo) error {
	if provInfo.ID != pm.self { // don't add own addrs.
		pm.pstore.AddAddrs(provInfo.ID, provInfo.Addrs, peerstore.ProviderAddrTTL)
	}
	prov := &addProv{
		ctx: ctx,
		key: k,
		val: provInfo.ID,
	}
	select {
	case pm.newprovs <- prov:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}
```

this channel is read by
```
func (pm *ProviderManager) run(ctx context.Context, proc goprocess.Process) {
```
and in the goroutine dump, i see this (*ProviderManager).run running fine (in fact there are two instances?)

in any case i'm having deep fun :)

**Comment by p4u** [comment]
So... since we relesed Azeno as production (almost 7 days), the leak is gone... I'm not sure why, the only thing I can think about is the ProcessArchive, which was adding previous elections to the IPNS archive (thus distributing it among the ipfsSync cluster). But I'm not confident regarding this being the cause. Actually I'd vote NO.

![image](https://user-images.githubusercontent.com/1075446/197883607-19e27a82-6171-4a5f-8016-5963db0324a5.png)

**Comment by altergui** [comment]
if it reappears, we can reopen this issue
