### ISSUE TITLE
bug: sql errors in http responses

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/vocdoni-node#817]
**Describe the bug**
GET calls to `v2/elections/:hash` are failing and returning SQL errors in the response.

**To Reproduce**

- endpoint used: https://api-dev.vocdoni.net/v2/
- ~~try fetching any election. So far all the ones I've tried were failing, even recently created ones.~~ use the ones I provide below because since a recent change new elections can be properly fetched.

Here's a curl example (copy-pasted from browser) for one recently created, in this case the sql error is `no rows in result set`:

~~~bash
curl 'https://api-dev.vocdoni.net/v2/elections/c5d2460186f738d2bc91b89928f78cbab3e4b1949e28787ec7a3020000000000' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: ca,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Origin: https://vocdoni.github.io' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers'
~~~

This one is from an existing process created a few days ago, in this case returns an error about converting a value from string to int64:

~~~
curl 'https://api-dev.vocdoni.net/v2/elections/c5d2460186f7d5d7fe684134f063b699719de9aaf2a308f7ad58020000000000' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: ca,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Origin: http://localhost:5173' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'TE: trailers'
~~~

Here's the full sql error of this call:

~~~
sql: Scan error on column index 29, name \"source_network_id\": converting driver.Value type string (\"UNKNOWN\") to a int64: invalid syntax
~~~

**Current behavior**
I think there are at least two issues here:
- an underlying issue related to sql, since one of the calls returns an error of typing with a column.
- the fact that sql errors maybe should not be visible via http requests

**Expected behavior**
The calls should be returning the json data of existing elections, so... the expected behavior is to work as expected 😄 

**Additional context**
The most recently created process was made via the sdk example, in case you wanna give it a fast try: https://vocdoni.github.io/vocdoni-sdk/

**Comment by elboletaire** [comment]
I've updated the title because since some recent changes the column issue disappeared. But sql errors are still thrown as http responses, for example in this case:

https://api-dev.vocdoni.net/v2/elections/c5d2460186f7d5d7fe684134f063b699719de9aaf2a308f7ad58020000000000

**Comment by altergui** [comment]
gave a quick look at this,
```
curl 'https://api-dev.vocdoni.net/v2/elections/0000000000000000000000000000000000000000000000000000000000000000'
```

returns
`{"error":"cannot fetch electionID 0000000000000000000000000000000000000000000000000000000000000000: sql: no rows in result set"}
`

so i'd say election [c5d2460186f7d5d7fe684134f063b699719de9aaf2a308f7ad58020000000000](https://api-dev.vocdoni.net/v2/elections/c5d2460186f7d5d7fe684134f063b699719de9aaf2a308f7ad58020000000000) simply does not exist (it was not created, due to whatever reason, for example the NewProcessTx failed due to nonce, or lack of balance, or whatnot)

**Comment by altergui** [comment]
regarding the "sql errors maybe should not be visible via http requests", i have no opinion (i'm lacking context / authority) but this specific "sql: no rows in result set" i do agree it's not very helpful, a simple "cannot fetch electionID xxxx: not found in database" (along with error code 404?) would be better

**Comment by altergui** [comment]
@p4u addressed exactly this in https://github.com/vocdoni/vocdoni-node/commit/1ede198#diff-8a1c97a3c76047a21682fceabcf8e05e4fdb9b8909d5e2209ec1fa626e153466R173-R175
https://github.com/vocdoni/vocdoni-node/blob/d078639c718ff9683d95be0b997bb2802d2589b4/api/elections.go#L173-L175

but i'm not sure it handles the "no rows in result set" since 	`ErrProcessNotFound = fmt.Errorf("process not found")` (i believe this changed with the indexer refactoring)

in any case, we're in the middle of refactoring the error handling and taking this report into account :grin: thanks bolet!

**Comment by altergui** [comment]
indeed, thannks to pau, at current master we're no longer returning sql errors but a simple 404

```
curl 'http://127.0.0.1:9090/v2/elections/0000000000000000000000000000000000000000000000000000000000000000'  -v
*   Trying 127.0.0.1:9090...
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
> GET /v2/elections/0000000000000000000000000000000000000000000000000000000000000000 HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 1
< Content-Type: application/json
< Vary: Origin
< Date: Wed, 22 Feb 2023 13:49:39 GMT
< 

* Connection #0 to host 127.0.0.1 left intact
```
